# Generated by Django 5.0.2 on 2024-02-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serpapi_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobResult',
        ),
    ]
